version: "2"
services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
    ports:
      - "9000:9000"
    environment:
      - TZ=${TZ}

  plexms:
    container_name: plexms
    restart: always
    image: plexinc/pms-docker
    volumes:
      - ${USERDIR}/docker/plexms:/config
      - ${USERDIR}/Downloads/plex_tmp:/transcode
      - ${USERDIR}/video:/media
      - ${USERDIR}/photos:/photos
      - ${USERDIR}/docker/certs:/certs
    network_mode: host
    environment:
      - TZ=${TZ}
      - HOSTNAME="homeserver"
      - PLEX_CLAIM="claim-8rypNKB835U7zZMMkSAA"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://192.168.1.24:32400/"

  transmission:
    container_name: transmission
    restart: always
    image: linuxserver/transmission
    volumes:
      - ${USERDIR}/docker/transmission:/config
      - ${USERDIR}/Downloads:/downloads
      - ${USERDIR}/Downloads/watch:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      
  organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/certs:/certs
    ports:
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  homeassistant:
    container_name: homeassistant
    restart: always
    image: homeassistant/home-assistant
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ${USERDIR}/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/certs:/certs
    network_mode: host
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  nodered:
    container_name: nodered
    image: nodered/node-red-docker
    ports:
      - "1880:1880"
    restart: always

  radarr:
    container_name: radarr
    restart: always
    image: linuxserver/radarr
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - ${USERDIR}/Downloads:/downloads
      - ${USERDIR}/video/Movies:/movies
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  jackett:
    container_name: jackett
    restart: always
    image: linuxserver/jackett
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - ${USERDIR}/docker/jackett/blackhole:/downloads
    ports:
      - "9117:9117"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}   

  ghost:
    container_name: ghost
    restart: always
    image: ghost:latest
    volumes:
      - /home/adam/ghost:/var/lib/ghost/content
    ports:
      - "2368:2368"
    environment:
      - url=http://adamfox.me
